# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

adjectives=['Accessible',
'Advanced',
'Ambiguous',
'Annoying',
'Appealing',
'Approachable',
'Attractive',
'Awkward',
'Boring',
'Bright',
'Business-like',
'Busy',
'Clean',
'Clear',
'Cluttered',
'Compelling',
'Complex',
'Comprehensive',
'Confusing',
'Consistent',
'Contradictory',
'Controllable',
'Convenient',
'Counter-intuitive',
'Creative',
'Credible',
'Cutting edge',
'Dated',
'Desirable',
'Difficult',
'Distracting',
'Dull',
'Easy to use',
'Effective',
'Efficient',
'Effortless',
'Empowering',
'Energetic',
'Engaging',
'Entertaining',
'Exciting',
'Expected',
'Familiar',
'Fast',
'Faulty',
'Flexible',
'Fresh',
'Friendly',
'Frustrating',
'Fun',
'Hard to Use',
'High quality',
'Illogical',
'Impressive',
'Inadequate',
'Incomprehensible',
'Inconsistent',
'Ineffective',
'Innovative',
'Insecure',
'Intimidating',
'Intuitive',
'Irrelevant',
'Meaningful',
'Misleading',
'Motivating',
'New',
'Non-standard',
'Obscure',
'Old',
'Ordinary',
'Organised',
'Overwhelming',
'Patronising',
'Poor quality',
'Powerful',
'Predictable',
'Professional',
'Relevant',
'Reliable',
'Responsive',
'Rigid',
'Satisfying',
'Secure',
'Simple',
'Simplistic',
'Slow',
'Sophisticated',
'Stable',
'Stimulating',
'Straightforward',
'Stressful',
'System-oriented',
'Time-consuming',
'Time-saving',
'Too technical',
'Trustworthy',
'Unattractive',
'Unconventional',
'Understandable',
'Unpredictable',
'Unrefined',
'Usable',
'Useful',
'Vague'
]
adjectives.each do |type|
  Adjective.find_or_create_by_adjective(type)
end

words=['TaskFlow',
       'String',
       'DropFlow']
words.each do |word|
  Word.find_or_create_by_word(word)
end
